name:                multiformats
version:             0.1.0.0
github:              "LibreCybernetics/multiformats-hs"
license:             OtherLicense
author:              "LibreCybernetics"

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base       >= 4.12     && < 5
- bytestring >= 0.10.8.2 && < 1
- text       >= 1.2.3.1  && < 2

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
    - basen

executables:
  multiformats-app:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multiformats

tests:
  multiformats-test:
    main:        TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multiformats
    - quickcheck-instances
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-quickcheck
